### PR TITLE
Add contributors and owners to README.md

### PR DESCRIPTION
**Pull request by trimble-iwelch**

### CODE REVIEW

**Comment by trimble-iwelch** [comment]
@jeffdoolittle  I created this PR per an action I took from our last devguide meeting.

**Comment by coliff** [comment]
heya. we agreed a [little while back to remove our names](https://github.com/trimble-oss/devguide/pull/180) and emails from the README, so I don't think we should add them back.

**Comment by trimble-iwelch** [comment]
@coliff I don't see a rationale as to why we removed names in that PR, only that we removed them and replaced them with a group mailing address.  What was the rationale?

Whatever we decide, we will need to update our inner source guidelines as they explicitly call out having Owners and Trusted Committers in the `README.md` file.

**Comment by coliff** [comment]
As discussed and agreed on chat, we removed the email addresses but kept the names. I'll approve and merge it now - thanks!

**Pull request merged**
